version: '3.8'
volumes:
  db-store:
services:
  nginx:
    image: nginx:1.19.4-alpine
    container_name: nginx
    volumes:
      - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/app
    links:
      - php
    depends_on:
      - php
    ports:
      - "8000:80"
  php:
    container_name: php
    build:
      context: .
      dockerfile: ./Docker/php/Dockerfile
    volumes:
      - ./src:/var/www/app
      - ./Docker/php/php.ini:/usr/local/etc/php/php.ini
    links:
      - mysql
    depends_on:
      - mysql
    environment:
      - DB_HOST=database
      - DB_DATABASE=php
      - DB_USERNAME=root
      - DB_PASSWORD=root
  mysql:
    container_name: mysql
    build:
      context: .
      dockerfile: ./Docker/mysql/Dockerfile
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: passw0rd

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: 'mysql'
    ports:
      - 18888:80

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
      - "1025:1025"